stages:
  - test
  - deploy

test:api:
  stage: test
  script:
    - cd api/TodoAPI
    - dotnet restore
    - dotnet test --no-restore --verbosity normal
  tags:
    - homeserver
  only:
    - master
    - merge_requests

test:front:
  stage: test
  script:
    - cd front
    - npm ci
    - npm run lint
  tags:
    - homeserver
  only:
    - master
    - merge_requests

deploy:
  stage: deploy
  script:
    - docker compose down
    - docker compose build --no-cache
    - docker compose up -d
    - docker image prune -f
  tags:
    - homeserver
  only:
    - master
